### ISSUE TITLE
Assembly "Neo4jClient" uses a higher version than the referenced assembly "Neo4j.Driver"

### ISSUE THREAD

**Issue by DarthSonic** [neo4j/neo4j-dotnet-driver#557]
When I update the driver package from 4.3.1 to 4.3.2 I get the following exception:

`Error CS1705: Assembly "Neo4jClient" mit Identität "Neo4jClient, Version=4.1.15.0, Culture=neutral, PublicKeyToken=null" verwendet "Neo4j.Driver, Version=4.3.67.1, Culture=neutral, PublicKeyToken=b646bc66d277ac07" mit einer höheren Version als die referenzierte Assembly "Neo4j.Driver" mit Identität "Neo4j.Driver, Version=4.3.2.2, Culture=neutral, PublicKeyToken=b646bc66d277ac07".`

Auto translated:

`Error CS1705: Assembly "Neo4jClient" with identity "Neo4jClient, Version=4.1.15.0, Culture=neutral, PublicKeyToken=null" uses "Neo4j.Driver, Version=4.3.67. 1, Culture=neutral, PublicKeyToken=b646bc66d277ac07" with a higher version than the referenced assembly "Neo4j.Driver" with identity "Neo4j.Driver, Version=4.3.2.2, Culture=neutral, PublicKeyToken=b646bc66d277ac07".`

**Comment by DarthSonic** [comment]
Okay. Found solution:

**Comment by AndyHeap-NeoTech** [comment]
Hi, thanks for posting the follow up solution.

**Comment by DarthSonic** [comment]
I think there is still a problem:
https://github.com/DotNet4Neo4j/Neo4jClient/issues/421

It seems to be a wrong version number in 4.3.1 that is fixed in 4.3.2 but then does break current neo4jclient.
